RoomsApplication/RoomsApplication/Models/RoomViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RoomsApplication.Models
{
    public class RoomViewModel
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public int MaxHumanCount { get; set; }
    }
}

RoomsApplication/RoomsApplication/Controllers/RoomsController.cs
using AutoMapper;
using Rooms.Domain.Contracts;
using Rooms.Domain.Models;
using Rooms.Domain.Services;
using RoomsApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RoomsApplication.Controllers
{
    public class RoomsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRoomsService _roomService;

        public RoomsController()
        {
            _roomService = new RoomService(); 

            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<RoomModel, RoomViewModel>();
                cfg.CreateMap<RoomPostModel, RoomModel>();
                cfg.CreateMap<RoomViewModel, GetRoomViewModel>();
            });
            _mapper = new Mapper(config);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RoomPostModel model)
        {
            var createModel = _mapper.Map<RoomModel>(model);

            _roomService.Create(createModel);

            return new EmptyResult();
        }

        public ActionResult GetAll()
        {
            var rooms = _roomService.GetAll();
            var roomsVM = _mapper.Map<List<RoomViewModel>>(rooms);

            var result = new GetRoomViewModel
            {
                Rooms = roomsVM
            };

            return View(result);
        }
    }
}

RoomsApplication/RoomsApplication/Views/Rooms/Create.cshtml
@model RoomsApplication.Models.RoomViewModel

@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm("Create", "Rooms", FormMethod.Post))
{
    <h1>This is Create Room Page</h1>
    <br />
    <div>
        @Html.LabelFor(x => x.Color)
    </div>
    <div>
        @Html.TextBoxFor(x => x.Color)
    </div>
    <br />
    <div>
        @Html.LabelFor(x => x.MaxHumanCount)
    </div>
    <div>
        @Html.TextBoxFor(x => x.MaxHumanCount)
    </div>
    <br />
    <input type="submit" value="Отправить" />
}

RoomsApplication/RoomsApplication/Views/Rooms/GetAll.cshtml
@model RoomsApplication.Models.GetRoomViewModel

@{
    ViewBag.Title = "Rooms";
}

<h2>This is all rooms we have:</h2>

<ul>
    @foreach (var room in Model.Rooms)
    {
        <li>ID: @room.Id Color: @room.Color</li>
    }
</ul>