RoomsApplication/RoomsApplication/Models/HumanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RoomsApplication.Models
{
    public class HumanViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PhoneNumber { get; set; }
        public int RoomId { get; set; }
    }
}

RoomsApplication/RoomsApplication/Controllers/HumansController.cs
using AutoMapper;
using Rooms.Domain.Contracts;
using Rooms.Domain.Models;
using Rooms.Domain.Services;
using RoomsApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RoomsApplication.Controllers
{
    public class HumansController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IHumansService _humanService;

        public HumansController()
        {
            _humanService = new HumanService();

            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<HumanModel, HumanViewModel>();
                cfg.CreateMap<HumanPostModel, HumanModel>();
                cfg.CreateMap<HumanViewModel, GetHumanViewModel>();
            });
            _mapper = new Mapper(config);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HumanPostModel model)
        {
            var createModel = _mapper.Map<HumanModel>(model);

            _humanService.Create(createModel);

            return new EmptyResult();
        }

        public ActionResult AddToRoom()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddToRoom(int humanId, int roomId)
        {
            _humanService.AddToRoom(humanId, roomId);

            return new EmptyResult();
        }

        public ActionResult GetHumanByRoomId(int id)
        {
            var humans = _humanService.GetHumanByRoomId(id);
            var humansVM = _mapper.Map<List<HumanViewModel>>(humans);

            var result = new GetHumanViewModel
            {
                Humans = humansVM
            };

            return View(result);
        }

        public ActionResult GetAll()
        {
            var humans = _humanService.GetAll();
            var humansVM = _mapper.Map<List<HumanViewModel>>(humans);

            var result = new GetHumanViewModel
            {
                Humans = humansVM
            };

            return View(result);
        }
    }
}

RoomsApplication/RoomsApplication/Views/Humans/AddToRoom.cshtml
@model RoomsApplication.Models.HumansToRoomsViewModel

@{
    ViewBag.Title = "AddToRoom";
}
@using (Html.BeginForm("AddToRoom", "Humans", FormMethod.Post))
{
    <h1>This is Add Human to Room Page</h1>
    <br />
    <div>
        @Html.LabelFor(x => x.HumanId)
    </div>
    <div>
        @Html.TextBoxFor(x => x.HumanId)
    </div>
    <br />
    <div>
        @Html.LabelFor(x => x.RoomId)
    </div>
    <div>
        @Html.TextBoxFor(x => x.RoomId)
    </div>
    <br />
    <input type="submit" value="Отправить" />
}

RoomsApplication/RoomsApplication/Views/Humans/Create.cshtml
@model RoomsApplication.Models.HumanViewModel

@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm("Create", "Humans", FormMethod.Post))
{
    <h1>This is Create Human Page</h1>
    <br />
    <div>
        @Html.LabelFor(x => x.Name)
    </div>
    <div>
        @Html.TextBoxFor(x => x.Name)
    </div>
    <br />
    <div>
        @Html.LabelFor(x => x.PhoneNumber)
    </div>
    <div>
        @Html.TextBoxFor(x => x.PhoneNumber)
    </div>
    <br />
    <div>
        @Html.LabelFor(x => x.RoomId)
    </div>
    <div>
        @Html.TextBoxFor(x => x.RoomId)
    </div>
    <br />
    <input type="submit" value="Отправить" />
}

RoomsApplication/RoomsApplication/Views/Humans/GetAll.cshtml
@model RoomsApplication.Models.GetHumanViewModel

@{
    ViewBag.Title = "GetAll";
}
<h2>This is all humans:</h2>

<ul>
    @foreach (var human in Model.Humans)
    {
        <li>ID: @human.Id, Name: @human.Name, Phone number: @human.PhoneNumber</li>
    }
</ul>

RoomsApplication/RoomsApplication/Views/Humans/GetHumanByRoomId.cshtml
@model RoomsApplication.Models.GetHumanViewModel

@{
    ViewBag.Title = "GetHumanByRoomId";
}

<h1>This is all Humans In Room</h1>

<ul>
    @foreach (var human in Model.Humans)
    {
        <li>ID : @human.Id, Name : @human.Name, Phone number : @human.PhoneNumber</li>
    }
</ul>